fixtures:
  forge_modules:
    stdlib:       "puppetlabs/stdlib"
    java:         "puppetlabs/java"
    wget:         "puppet/wget"
    yumrepo_core: "puppetlabs/yumrepo_core"
  symlinks:
    artifactory: "#{source_dir}"
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git@github.com:puppetlabs/provision.git'
